version: "3.2"

services:
  webserver:
    build: 
      context: ./bin/php74
    container_name: php74
    restart: 'always'
    links: 
      - database
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    ports:
      - "80:80"
      - "443:443"
  database:
    build:
      context: "./bin/mysql"
    container_name: 'database'
    restart: 'always'
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: coder
      MYSQL_DATABASE: aplex
      MYSQL_USER: developer
      MYSQL_PASSWORD: 19052000
    ports:
      - "127.0.0.1:3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: developer
      PMA_PASSWORD: 19052000
      MYSQL_ROOT_PASSWORD: coder
      MYSQL_USER: developer
      MYSQL_PASSWORD: 19052000
    volumes: 
      - /sessions
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    ports:
      - '8080:80'
  redis:
    container_name: 'redis'
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
